cxx_library(
    name = 'llist',
    header_namespace = 'llist',
    exported_headers = subdir_glob([
        ('include', '**/*.h'),
    ]),
    srcs = glob([
        'src/**/*.c',
    ]),
    visibility = [
        '//...',
    ],
    compiler_flags = [
        '-g',
    ],
)
